language: java
install:
  - cd /tmp
  - git clone https://github.com/facebook/buck.git
  - cd buck
  - ant
  - cd $TRAVIS_BUILD_DIR
script: /tmp/buck/bin/buck test --all
jdk:
  - openjdk7
  - oraclejdk7
